version: '3.8'

services: 
  jleague-db:
    build: ./jleague-db
    ports: 
      - 8030:3306
    volumes:
      - ./jleague-db/db-data:/jleague/var/lib/mysql
  jleague-batch:
    build: ./jleague-batch
    ports:
      - 8070:8070
    environment: 
      DB_HOST: jleague-db
      DB_USER: user
      DB_DATABASE: jleague-app
      DB_PASSWORD: password
