version: '3.8'

services:
  jleague-db:
    build: ./jleague-db
    ports:
      - 8030:3306
    volumes:
      - ./jleague-db/db-data:/var/lib/mysql
  jleague-batch:
    build: ./jleague-batch
    environment:
      DB_HOST: jleague-db
      DB_USER: user
      DB_DATABASE: jleague-app
      DB_PASSWORD: password
    volumes:
      - ./jleague-batch:/application
  jleague-api:
    build: ./jleague-api
    ports:
      - 8070:8070
    environment:
      FLASK_APP: app.py
      FLASK_ENV: local
      DB_HOST: jleague-db
      DB_USER: user
      DB_DATABASE: jleague-app
      DB_PASSWORD: password
    command: flask run --host=0.0.0.0 --port=8070
    volumes:
      - ./jleague-api:/application